### ISSUE TITLE
Dont execute /sneeze and other commands that use ther chat box.

### ISSUE THREAD

**Issue by ketonic** [mrhoffmann/idler#1]
Opens the chatbox, types the command but dont press the final enter to execute it.

**Comment by mrhoffmann** [comment]
Please provide if this is by using the executable or the script. Either way atm, please download the newly added as of now.

**Comment by mrhoffmann** [comment]
If the issue persists, please open any text-editor to edit the .ahk-file, replace 30000 in the opening by 1000. Now open a new file and wait for the script to start outputing data. The output should look like:

```
/sit
wslljlccccjjlcc
/dance
ws
/sleep
ws
/sleep
ws
/sneeze
wscmc
/sneeze
ws
```

Please note that ws can be followed by b, c, j, l or m in a random order with a random number of occurences, as they doesn't require any enter-key to be pressed before being executed, the output will be followed directly. This isn't an error.

**Comment by mrhoffmann** [comment]
Will close bug as the result was from using the executable and it wasn't properly compiled before pushing repo.
